### ISSUE TITLE
About head of depth estimating

### ISSUE THREAD

**Issue by hechengyuan** [dhk1349/seg-dinov2#1]
This code is a repository where you used dinov2 as the backbone and added an additional head to adapt it for segmentation tasks. Have you tried using a head for monocular depth estimation? Or do you have any insights on what adjustments can be made to better adapt it for the monocular depth estimation task?

**Comment by dhk1349** [comment]
Well, I am not familiar with the depth estimation task. But referring to the paper, it seems that following the DPT protocol would show fine performance. 
I am tuning DINO v2 on monocular depth estimation using a single linear layer and upsample scale of 4. It might not be as good as paer veriosn but If you are interested, take a look when training is done :)
